### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by timcnicholls** [percival-detector/framereceiver#1]
This is a test issue to check Mylyn integration. Ignore

**Comment by ulrikpedersen** [comment]
I've never used Mylyn before - does the integration work and is it useful?

**Comment by timcnicholls** [comment]
I've not used it in anger to be honest, as any issue trackers I've used in the past haven't played nicely with it. I was thinking about if/how we use GitHub for task/issue management for this project, and it got me thinking about Eclipse integration so I thought I'd try it! Seems to work quite nicely, although the web front-end GitHub is just as effective.

(This comment was submitted with Mylyn!)
