### ISSUE TITLE
Expose RX buffer size in configuration parsing

### ISSUE THREAD

**Issue by timcnicholls** [percival-detector/framereceiver#15]
The MacOSX travis build currently fails integration testing due to the RX buffer size being too large for the OS network stack defaults:

```
$ python bin/run_integration_test.py --frames=1 --interval=1.0 --timeout=30
Producer process OK completed with expected output
Failed to find expected output "Specified number of frames \(1\) received and released, terminating" for Receiver process. Output follows:
5 [0x7fff79d66300] DEBUG FrameReceiver null - Debug level set to  2
6 [0x7fff79d66300] DEBUG FrameReceiver null - Parsing configuration file test_config/fr_test.config
2015-10-27 22:14:06,763 DEBUG FrameReceiver - log4cxx config file is set to test_config/log4cxx.config
...snip...
2015-10-27 22:14:06,764 INFO  FrameReceiver - Created PERCIVAL emulator frame decoder instance
2015-10-27 22:14:06,781 DEBUG FrameReceiver - Initialised frame buffer manager of total size 840000000 with 100 buffers
2015-10-27 22:14:06,791 DEBUG FrameReceiver - Running RX thread service
2015-10-27 22:14:06,791 ERROR FrameReceiver - Frame receiver run failed: RX channel failed to set receive socket buffer size for port 8000 : No buffer space available
```

The buffer size is already present in the FrameReceiverConfig class and used in the receiver thread initialisation, just needs exposing to the config CLI/file parser. 

N.B. This was solved for the unit test fixture earlier - see commit 246753f38b6dd9c9db1f9aa321a7aeb411051f77).

**Comment by ulrikpedersen** [comment]
Sounds good. I did experience the same issue on my own mac when I was working on this yesterday but ran out of time to do anything about it... Now I'm back on Linux :smile:

**Comment by ulrikpedersen** [comment]
I figure it must also be possible to adjust the OSX network stack to configure more memory for UDP buffers... I found this message which may be relevant (I can't try it out for myself at the moment though): http://lists.apple.com/archives/darwin-kernel/2012/Apr/msg00042.html

**Comment by timcnicholls** [comment]
I think we're losing sight of the priority of an OS X build by going that far. We're never going to realistically push significant amounts of data at a frameReceiver on a Mac unless we start connect 10GigE interfaces to one. I think it is sufficient to do enough to allow the build and travis to succeed and use OS X as a useful cross-check of the code.

**Comment by ulrikpedersen** [comment]
This was mostly a personal interest in figuring out what is causing this network buffer issue on this OS - and how the network stack works.  :smile: 
I agree that just adding the CLI option to adjust the frameReceiver buffer size is good enough for our purpose where OSX is not really an official target.

**Comment by timcnicholls** [comment]
It would be great to hook a Mac up to a PERCIVAL detector head and take data though... :wink:
