### ISSUE TITLE
Update build and run instructions

### ISSUE THREAD

**Issue by ulrikpedersen** [percival-detector/framereceiver#20]
In preparation for release 0.1 we also need to update the build and run instructions in the README.md
- [x] @ulrikpedersen: instructions for the File Writer application
- [x] @timcnicholls: instructions for the frameReceiver application

**Comment by timcnicholls** [comment]
Should also include the following:
- [x] Install HDF5 libraries, h5py package
- [x] Install and use mpirun to run multiple frameReceiver and fileWriter instances

**Comment by ulrikpedersen** [comment]
Agree. I see that the HDF group provide CentOS RPMs, which is probably the most sys-admin-friendly form of distribution: https://www.hdfgroup.org/HDF5/release/rpms.html

However, from the filename it seems to include the szip library which I have not added to the cmake list of libraries. Not sure if the build will Just Work without specifying szip... Could you try out the RPM installation on your system @timcnicholls?

**Comment by timcnicholls** [comment]
Yes, works fine (see slack channel)

**Comment by ulrikpedersen** [comment]
Deferring the mpirun subtask to new ticket #40
