### ISSUE TITLE
file writer: pipeline functions

### ISSUE THREAD

**Issue by ulrikpedersen** [percival-detector/framereceiver#28]
The obvious steps for parallizing in a pipeline:
- Listen for new frame ready from frameReceiver
- Copy data from SHM buffer to local frame
- Write frame to file on disk

Deferred from issue #17 as this is a performance optimization which is not really required for milestone "Version 0 delivery".

**Comment by timcnicholls** [comment]
This issue was moved to percival-detector/odin-data#5
