### ISSUE TITLE
Add frame counter to frameReceiver

### ISSUE THREAD

**Issue by timcnicholls** [percival-detector/framereceiver#3]
In order to facilitate automated integration testing in travis-ci with a chain of frame producer, receiver and processor, the frameReceiver should be capable of receiving a fixed number of frames and then terminating cleanly. This number should be a command-line or configuration file parameter.

**Comment by ulrikpedersen** [comment]
The addition of the -f,--frames option on the frameReceiver application in commit 29140fa404eab108b7618db6ccc2d6d9fa36e54f complete this enhancement.
